### ISSUE TITLE
create-db fails to build when --with-sqlite is used

### ISSUE THREAD

**Issue by adedov** [KoreLogicSecurity/libpathwell#1]
I used following command line to call configure:

./configure --with-gmp=/home/adedov/.local --with-pcre=/home/adedov/.local --with-sqlite=/home/adedov/.local/

So, libpathwell has been built successfully, but create-db failed because it does not used build settings specified to configure:

make[2]: Entering directory `/home/adedov/meter-study/meters/libpathwell-0.6.1/src/create-db'
gcc -DHAVE_CONFIG_H -I. -I../../include     -O3 -MT create-db.o -MD -MP -MF .deps/create-db.Tpo -c -o create-db.o create-db.c
In file included from app-includes.h:21,
                 from all-includes.h:25,
                 from create-db.c:18:
../../include/pathwell.h:38:21: error: sqlite3.h: No such file or directory

The same issue for all other subprojects.

**Comment by KoreLogicSecurity** [comment]
Ah, thanks for reporting this, we will investigate.

It probably should not matter since you are (trying to) specifying everything on the configure line, but, what OS & version are you attempting to build on?

Thanks!

**Comment by adedov** [comment]
Scientific Linux release 6.6. I am not root on the machine, so have to install includes/.so file links locally.

**Comment by adedov** [comment]
I'd be very appreciated to be able to build under OS X as well. I.e. disable PAM module building.

**Comment by KoreLogicSecurity** [comment]
We are attempting to replicate the error. What was the exact version of SQLite you installed under /home/adedov/.local (please provide the name of the distribution tar ball)? Also, do you see the sqlite3.h header file under /home/adedov/.local/include?

**Comment by adedov** [comment]
Yes, I see sqlite3.h there. The problem is that neither of submodules' Makefile include sqlite_cflags, pcre_flags, etc into INCLUDES variable.

As a result I had to include row like "INCLUDES = -I/home/adedov/.local/include" into Makefile from create-db and some other subprojects to make them building.

**Comment by KoreLogicSecurity** [comment]
We were unable to reproduce that issue on our build platform (Gentoo Linux) using a PREFIX of /tmp/local, so the issue is most likely a configure issue specific to your build platform/environment. For reference, we built GMP 6.0.0a, PCRE 8.37, SQLite 3.8.11.1, and PathWell using gcc 4.9.2. If you can provide additional details like the versions of each package built along with the commands used to configure and compile each, it would help us isolate the issue quicker. We'll also look into setting up a Scientific Linux build platform/environment to see if we can reproduce the issue.

**Comment by adedov** [comment]
I am not sure if using custom PREFIX emulates situation. You need machine without include files for sqlite in system-wide location (/usr/include), for example. After that try to run configure --with-sqlite=custom-location. So, even if configure works well, built for create-db may fail.

**Comment by KoreLogicSecurity** [comment]
A fix is in the works. We'll post an update when it's ready.

**Comment by adedov** [comment]
Thanks!

**Comment by KoreLogicSecurity** [comment]
This issue should be resolved in the 0.6.2 release, which has just been pushed. Thanks for bringing it to our attention.
