### ISSUE TITLE
Simple test utility.

### ISSUE THREAD

**Issue by adedov** [KoreLogicSecurity/libpathwell#2]
Hello!

Not sure if it is "issue" or even valid feature request.

Is it possible to create simple test utility that would check passwords without PAM against some sane defaults? Or may be utility that accept list of blacklisted topologies and clear answer: pass, fail.

I'd like to test your approach and compare to other password polices, see http://password-policy-testing.wikidot.com/. Does it make sense to do such testing against your library at all? 

Thanks

**Comment by KoreLogicSecurity** [comment]
Yes, this is possible. It's also something that we already have in the works. Our goal is to include it in our next minor release (i.e., 0.7.0). We'll post an update once an official release date has been set. Thanks for the feature request.

**Comment by adedov** [comment]
Thanks a lot!

**Comment by KoreLogicSecurity** [comment]
This issue should be resolved in the 0.7.0 release, which has just been pushed. The pathwell-chkpw utility tests a user-specified password or password pair (old/new) for conformance with the various PathWell enforcement checks (e.g., minlen, minlev, maxuse, etc.). Diagnostic information is then written to stdout. Refer to the corresponding man page for additional details.
